config/routes.rb
Rails.application.routes.draw do

    namespace :mercury do
      resources :images
    end
  get "/", to: redirect('/home'), as: 'home'

  get "admin", to: "admin#index", as: 'admin_index'
  post "admin/login", to: "admin#login", as: 'admin_login'

  get "Gallery", to: "gallery#index", as: 'gallery_index'

  get "/Food", to: "site#dishes", as: 'dishes'
  put "/Food", to: "site#update_dishes", as: 'update_dishes'
  get "/:title", to: "site#page", as: 'page'
  put "/:title", to: "site#update_page", as: 'update_page'

  mount Mercury::Engine => '/'
  Mercury::Engine.routes

  root :to => 'site#home'
  

end

app/models/dish.rb
class Dish < ActiveRecord::Base
end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
end

app/models/mercury/image.rb
class Mercury::Image < ActiveRecord::Base

  self.table_name = :mercury_images
  

  has_attached_file :image, :styles => { :medium => "600x400>", :thumb => "100x100>" }, :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :dropbox_options => {environment: ENV["RACK_ENV"]}
       

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  delegate :url, :to => :image

  def serializable_hash(options = nil)
    options ||= {}
    options[:methods] ||= []
    options[:methods] << :url
    super(options)
  end

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password 
	before_save :encrypt_password
	after_save :clear_password

	def encrypt_password
		if password.present?
			self.salt = BCrypt::Engine.generate_salt
			self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
		end
	end
	def clear_password
		self.password = nil
	end

	def self.authenticate(username="", login_password="")

		user = find_by username: username

		if user && user.match_password(login_password)
			return user
		else
			return false
		end
	end

	def match_password(login_password="")
		encrypted_password == BCrypt::Engine.hash_secret(login_password, self.salt)
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :authenticate_user, :except => [:index, :login]

  def index
    # Displays the login form.
  end

  def login
    authorized_user = User.authenticate(params[:username],params[:password])
    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = "You are logged in as #{authorized_user.username}"
      redirect_to '/editor/Home'
    else
      flash[:notice] = "Invalid Username or Password"
      flash[:color]= "invalid"
      render "index"  
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to :action => 'index'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected 

  
  def authenticate_user
    if session[:user_id]
      # set current user object to @current_user object variable
      @current_user = User.find session[:user_id] 
      return true 
    else
      redirect_to(:controller => 'sessions', :action => 'login')
      return false
    end
  end

  def save_login_state
    if session[:user_id]
      redirect_to(:controller => 'sessions', :action => 'home')
      return false
    else
      return true
    end
  end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
  end
end

app/controllers/mercury/images_controller.rb
class Mercury::ImagesController < MercuryController

  respond_to :json

  # POST /images.json
  def create
    
    @image = Mercury::Image.new(params.require(:image).permit(:image))
    @image.save
    respond_with @image
  end

  # DELETE /images/1.json
  def destroy
    @image = Mercury::Image.find(params[:id])
    @image.destroy
    respond_with @image
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
 

  def page
  	find_page
  	logger.info "Page Found: #{@page.text}"
  end

  def update_page
    find_page
    page_text = (params[:content]) [:page_text]
    logger.info "page_text: #{page_text}"
    @page[:text] = page_text[:value]
    @page.save!
    render :text => '{}'
  end

  def dishes
    @dishes = Dish.all.order(:id)
    session[:dishes] = @dishes.map { |dish| dish.name }
  end

  def update_dishes
    content = params[:content]
    page_text = content[:food_header]

    (0..3).each do |n|
      dish_full = content["dish_text_#{n}"][:value].split('.')
      dish_title = dish_full[0]
      dish_text = dish_full[1]
      dish_img = content["dish_img_#{n}"][:attributes][:src]
      logger.info "Saving Dish Image: #{dish_img}, Title: #{dish_title}"
      dish = Dish.find_by_name session[:dishes][n]
      dish[:name] = dish_title
      dish[:text] = dish_text
      dish[:image] = dish_img
      dish.save! 
      
    end
    render :text => '{}'

  end

  private

  def find_page
    @title = params[:title].capitalize
    logger.info "Page Title: #{@title}"
    @page = Page.find_by_title @title
  end

 
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/admin/index.html.haml
#login
  = form_tag(:action => :login) do
    #login-user
      = label_tag 'username'
      = text_field_tag :username
    
    #login-pass
      = label_tag 'password'
      = password_field_tag :password
    = submit_tag "Log In"

app/views/gallery/index.html.haml
.galleria
  

app/views/layouts/application.html.haml
!!! 5
%html
   
  %head
    %title= "La Cala Catering"
    %meta{ :charset => 'utf-8'}
    %meta{'http-equiv' => 'content-type', :content => "text/html;charset=UTF-8"}
    %meta{ :content => "Catering company based in Romsey, Hampshire, UK. Specialises in catering Spanish food and Spanish inspired food for all sort of events. Run by Masterchef 2011 finalist Anneliese Kiely", :name => "description" }
    -# Facebook stuff   
    %meta{ :content => "3 days", :name => "revisit-after" }
    %meta{:property=>"og:title" ,:content=>"La Cala Catering" }
    %meta{:property=>"og:type", :content=>"website" }
    %meta{ :property=>"og:url", :content=>"http://www.lacalacatering.com" }
    %meta{:property=>"og:image", :content=>"" }
    %meta{ :property=>"og:site_name", :content=>""}
    %meta{:property=>"fb:admins", :content=>"100003075374410"}
  
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true

    %link{ rel: "stylesheet", href: "/assets/galleria.classic.css"}

    %link{ rel: "shortcut icon", href: "/favicon.ico" }

  

    = javascript_include_tag "application", "data-turbolinks-track" => true

    = csrf_meta_tags

  %body
    %header
     
      
      .logo
        %a{ :href => "/"} 
          %img{:src => image_url('logo.jpg'), :alt => "La Cala Catering"}
      %iframe{:src=>"http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.lacalacatering.com&amp;send=false&amp;layout=standard&amp;width=450&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font&amp;height=80",
       :scrolling=>"no", :frameborder=>"0",
       :style=>"border:none; overflow:hidden; width:240px; height:40px; float:right; margin-top: -100px;" ,:allowTransparency=>"true"}
    #menu{:class => 'menu'}
      %ul
        %li 
          = link_to "Home", page_path('Home') 
            
        %li
          = link_to "Food", page_path('Food'), id: 'Food' 
            
        %li
          = link_to "About", page_path('About') 
            
        %li
          = link_to "Contact", page_path('Contact')

        %li
          = link_to "Gallery", gallery_index_path
            
          

    #content
      = yield    
      
    %footer
      %p
        Copyright 2014 La Cala Catering. All rights reserved.

app/views/layouts/mercury.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, maximum-scale=1.0, initial-scale=1.0"}
    = csrf_meta_tags
    %title La Cala Catering  - Admin
    = stylesheet_link_tag    'mercury'
    %script{:src => "//code.jquery.com/jquery-1.7.2.min.js"}
    = javascript_include_tag  'mercury'
  %body
    :javascript
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  null, // 'form', or 'json' (default json)
        saveMethod: null, // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });

      // Change the Navigation URLs for easy editing
      $(function() {
        $('#mercury_iframe').load(function() {
          console.log('Mercury iframe loaded');
          $('#menu a',$('#mercury_iframe').contents()).each(function() {
            var href =  this.attributes['href'].nodeValue;
            this.href = '/editor'+href;
          });
          
        });
      });

app/views/site/dishes.html.haml
%article
  
  %div{:class => "slider", :data =>{:"cycle-fx" => "scrollHorz", :"cycle-timeout" => "10000", "cycle-center-horz" => true, :"cycle-caption" => "#caption", :"cycle-caption-template" => "{{title}}"}} 
    - @dishes.each_with_index do |dish,index|
      %img{:id => "dish_img_#{index}",:src => dish[:image], :data => {:mercury => "image", :class => "mercury-region", :title => "#{dish[:name]}. #{dish[:text]}"}}
      .invisible{:id => "dish_text_#{index}", :style => "display:none", :data => {:mercury => "simple"}, :class => "mercury-region"}
        #{dish[:name]}. #{dish[:text]}

  #caption
      
              
      

app/views/site/page.html.haml
%article
  #page_text{:data => {:mercury => "full"}, :class => "mercury-region"}
    != @page[:text]